version: 0.2

phases:
  install:
    commands:
      - sudo su -
      - sudo amazon-linux-extras install epel
      - yum update -y
      - yum install ansible -y
      - echo "this code will be executed"
      - yum update -y
      - yum install -y httpd
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - cd /var/www/html
      - sudo curl  https://raw.githubusercontent.com/vasindran/HelloGitHub/blob/main/TestDemo.html
      - systemctl enable httpd
      - systemctl start httpd
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - TestDemo.html
    - scripts.sh
